Description:
  This template sets up the workshop application on an AutoScaling group,
  behind an Application Load Balancer, with a CodeDeploy application.
  The workshop will need one stack of this template per team.

Parameters:
  SharedResourceStack:
    Description: Name of an active CloudFormation stack that contains the shared workshop resources, such as the VPC.
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: GraceHopperWorkshopSharedResources
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/amzn-ami-hvm-x86_64-gp2"

Resources:
  LaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: false
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      SecurityGroups:
        - Fn::ImportValue:
            !Sub "${SharedResourceStack}:PrivateHttpIngressSecurityGroup"
      IamInstanceProfile:
        Fn::ImportValue:
          !Sub "${SharedResourceStack}:InstanceProfile"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum -y update
          yum install -y ruby git 
          cd /home/ec2-user
          #################
          # Clone GHC repo
          #################
          git clone https://github.com/ha-king/circle-ghc-workshop.git
          cd circle-ghc-workshop
          ######################
          # Install Dependencies
          ###################### 
          yum install -y httpd
          curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
          yum install -y nodejs
          #############################
          # NPM Build + Copy to Webroot
          #############################
          /bin/bash deployment_scripts/build_application
          /bin/bash deployment_scripts/copy_application
          ###############
          #  Start Apache
          ###############
          service httpd start
          #################
          # Start CWLogging  
          #################
          yum install -y awslogs gettext jq
          envsubst < config/awslogs.conf > /etc/awslogs/awslogs.conf
          AWS_REGION=`curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region`
          sed -i -e "s/region = us-east-1/region = $AWS_REGION/g" /etc/awslogs/awscli.conf
          service awslogs restart
          chkconfig awslogs on

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      MinSize: 3
      MaxSize: 3
      LaunchConfigurationName: !Ref LaunchConfig
      VPCZoneIdentifier:
        Fn::Split:
        - ","
        - Fn::ImportValue:
            !Sub "${SharedResourceStack}:PrivateSubnets"
      TargetGroupARNs:
        - Ref: LoadBalancerTargetGroup
      Tags:
        - Key: Name
          Value:
            Fn::ImportValue:
              !Sub "${SharedResourceStack}:WorkshopName"
          PropagateAtLaunch: true
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: true

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        -
          Type: forward
          TargetGroupArn:
            Ref: LoadBalancerTargetGroup
      LoadBalancerArn:
        Ref: LoadBalancer
      Port: 80
      Protocol: HTTP

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
        Fn::Split:
        - ","
        - Fn::ImportValue:
            !Sub "${SharedResourceStack}:PublicSubnets"
      SecurityGroups:
        - Fn::ImportValue:
            !Sub "${SharedResourceStack}:PublicHttpIngressSecurityGroup"

  LoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      UnhealthyThresholdCount: 2
      HealthyThresholdCount: 2
      HealthCheckPath: /
      Port: 80
      Protocol: HTTP
      VpcId:
        Fn::ImportValue:
          !Sub "${SharedResourceStack}:VPC"

Outputs:
  Url:
    Description: Workshop application URL
    Value:
      Fn::Sub: 'http://${LoadBalancer.DNSName}'
